CREATE database VEHICLE_SERVICING_RECORD;
USE VEHICLE_SERVICING_RECORD;
	CREATE TABLE `APPOINTMENT` (
    `SERVICE NUMBER` INTEGER,
    `APPOINTMENT NUMBER` INTEGER,
    `APPOINTMENT DAY` VARCHAR(10),
    `APPOINTMENT  DATE` DATE,
    `APPOINTMENT  TIME` TIME,
    `CUSTOMER ID` VARCHAR(255),
    PRIMARY KEY (`APPOINTMENT NUMBER`),
    KEY `FK` (`SERVICE NUMBER` , `CUSTOMER ID`)
);

CREATE TABLE `CUSTOMER` (
    `CUSTOMER ID` VARCHAR(255),
    `CUSTOMER FIRST NAME` VARCHAR(255),
    `CUSTOMER LAST NAME` VARCHAR(255),
    `VEHICLE NUMBER` VARCHAR(10),
    PRIMARY KEY (`CUSTOMER ID`),
    KEY `FK` (`VEHICLE NUMBER`)
);

CREATE TABLE `VEHICLE INFO` (
    `VEHICLE NUMBER` VARCHAR(10),
    `VEHICLE MODEL` VARCHAR(255),
    `VARIANT` VARCHAR(20),
    `VIN` VARCHAR(16),
    `ENGINE NUMBER` VARCHAR(6),
    PRIMARY KEY (`VEHICLE NUMBER`),
    KEY `FK` (`VIN`)
);

CREATE TABLE `VEHICLE ADDITIONAL INFORMATION` (
    `VEHICLE COLOR` VARCHAR(255),
    `VIN` VARCHAR(16),
    `DATE OF BUILD` DATE,
    `DATE OF PURCHASE` DATE,
    `TYPE OF OWNERSHIP` INTEGER,
    PRIMARY KEY (`VIN`)
);

CREATE TABLE `BILLING INFORMATION` (
    `INVOICE NUMBER` VARCHAR(20),
    `SERVICE NUMBER` INTEGER,
    `BILL AMOUNT` INTEGER,
    `BILL` BLOB,
    PRIMARY KEY (`INVOICE NUMBER`),
    KEY `FK` (`SERVICE NUMBER`)
);

CREATE TABLE `SERVICE INFORMATION` (
    `SERVICE NUMBER` INTEGER,
    `ODOMETER READING` INTEGER,
    `TYPE OF SERVICE` VARCHAR(255),
    `VEHICLE NUMBER` VARCHAR(10),
    `SERVICE DATE` DATE,
    PRIMARY KEY (`SERVICE NUMBER`),
    KEY `FK` (`VEHICLE NUMBER`)
);

CREATE TABLE `PICKUP INFORMATION` (
    `SERVICE NUMBER` INTEGER,
    `VEHICLE NUMBER` VARCHAR(10),
    `PICKUP DATE` DATE,
    `PICKUP TIME` TIME,
    `PICKUP ID` VARCHAR(10),
    PRIMARY KEY (`PICKUP ID`),
    KEY `FK` (`SERVICE NUMBER` , `VEHICLE NUMBER`)
);

CREATE TABLE `PICKUP ADDRESS` (
    `APARTMENT NUMBER` VARCHAR(10),
    `STREET NAME` VARCHAR(10),
    `CITY` VARCHAR(10),
    `STATE` VARCHAR(20),
    `ZIP` INTEGER,
    `PHONE NUMBER` INTEGER,
    `PICKUP ID` VARCHAR(10),
    PRIMARY KEY (`PHONE NUMBER`),
    KEY `FK` (`PICKUP ID`)
);

CREATE TABLE `BILLING INFORMATION LABOURCODE AND AMOUNT` (
    `BILCA ID` INTEGER,
    `INVOICE NUMBER` VARCHAR(20),
    `LABOUR CODE` VARCHAR(6),
    PRIMARY KEY (`BILCA ID`),
    KEY `FK` (`INVOICE NUMBER` , `LABOUR CODE`)
);

CREATE TABLE `COMPLAINT SOLUTIONS LABOUR CODE AND AMOUNT` (
    `CSLA ID` varchar(8),
    `COMPLAINT ID` INTEGER,
    `LABOUR CODE` VARCHAR(6),
    PRIMARY KEY (`CSLA ID`),
    KEY `FK` (`COMPLAINT ID` , `LABOUR CODE`)
);

CREATE TABLE `LABOUR CODE AND AMOUNT` (
    `LABOUR CODE` VARCHAR(6),
    `AMOUNT` INTEGER,
    `DESCRIPTION` TEXT,
    PRIMARY KEY (`LABOUR CODE`)
);

CREATE TABLE `COMPLAINTS AND SOLUTIONS` (
    `COMPLAINT ID` INTEGER,
    `JOB CARD NUMBER` INTEGER,
    `COMPLAINTS` TEXT,
    `SOLUTIONS` TEXT,
    PRIMARY KEY (`COMPLAINT ID`),
    KEY `FK` (`JOB CARD NUMBER`)
);

CREATE TABLE `JOB CARD INFO` (
    `JOB CARD NUMBER` INTEGER,
    `SERVICE NUMBER` INTEGER,
    PRIMARY KEY (`JOB CARD NUMBER`),
    KEY `FK` (`SERVICE NUMBER`)
);

CREATE TABLE `CONTACT INFORMATION` (
    `APARTMENT NUMBER` VARCHAR(5),
    `STREET NAME` VARCHAR(255),
    `CITY` VARCHAR(20),
    `STATE` VARCHAR(20),
    `ZIP` INTEGER,
    `CONTACT NUMBER` INTEGER,
    `EMAIL ID` VARCHAR(255),
    `CUSTOMER ID` VARCHAR(255),
    PRIMARY KEY (`EMAIL ID`),
    KEY `FK` (`CUSTOMER ID`)
);
SELECT 
    *
FROM
    APPOINTMENT;
SELECT 
    *
FROM
    vehicle_servicing_record.billing information;
SELECT 
    *
FROM
    vehicle_servicing_record.`billing information`;
SELECT 
    *
FROM
    vehicle_servicing_record.`billing information labourcode and amount`;
SELECT 
    *
FROM
    vehicle_servicing_record.`complaint solutions labour code and amount`;
SELECT 
    *
FROM
    vehicle_servicing_record.`complaints and solutions`;
SELECT 
    *
FROM
    vehicle_servicing_record.`contact information`; 
INSERT INTO vehicle_servicing_record.`appointment`
VALUES 
('12','14','MONDAY','2019/03/21','101010','BAR123');
SELECT 
    *
FROM
    vehicle_servicing_record.`APPOINTMENT`;
INSERT INTO vehicle_servicing_record.`BILLING INFORMATION`
VALUES 
('QER123','12','3000','');
 SELECT * FROM vehicle_servicing_record.`billing information`;
 INSERT INTO vehicle_servicing_record.`BILLING INFORMATION labourcode and amount`
values
('aebc1234', '1234','bml653');
select *  from  vehicle_servicing_record.`BILLING INFORMATION labourcode and amount`;
